configuration:
  template_dir:
    - "git://github.com/moremoban/pypi-mobans.git!/templates"
    - local
  configuration: config.yml
  configuration_dir: "repo://pypi-mobans/config"
targets:
  - mytravis.yml: travis.yml.jj2
  - test.txt: demo.txt.jj2
