configuration:
  template_dir:
    - "https://raw.githubusercontent.com/moremoban/pypi-mobans/dev/templates/"
    - local
  configuration: config.yml
  configuration_dir: >-
    https://raw.githubusercontent.com/moremoban/pypi-mobans/dev/config/
targets:
  - mytravis.yml: travis.yml.jj2
  - test.txt: demo.txt.jj2
