targets:
  - a.output: a.template
  - b.output: b.template
extensions:
  jinja2:
    - jinja2.ext.with_
    - filter:moban.externals.file_system.url_join
    - test:moban.externals.file_system.exists
    - global:description=moban.constants.PROGRAM_DESCRIPTION