requires:
   - pypi-mobans-pkg
configuration:
  template_dir:
    - "pypi-mobans-pkg:templates"
    - local
  configuration: config.yml
  configuration_dir: "pypi-mobans-pkg:config"
targets:
  - mytravis.yml: travis.yml.jj2
  - test.txt: demo.txt.jj2
