configuration:
  configuration_dir: 'custom-config'
  template_dir:
    - custom-templates
    - cool-templates
    - '.'
  template: a.template.jj2
targets:
  - output: a.output
    configuration: data.yml
  - output: a.output2
    configuration: data2.yml
