configuration:
  template_dir:
    - template-sources
targets:
  - destination: simple.file.copy
    source: file-in-template-sources-folder.txt
    action: copy
  - destination: "misc-1-copying/can-create-folder/if-not-exists.txt"
    source: file-in-template-sources-folder.txt
    action: copy
  - destination: "test-dir"
    source: dir-for-copying
    action: copy
  - destination: "test-recursive-dir"
    source: dir-for-recusive-copying/**
    action: copy
