name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9-dev]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          make install_test format git-diff-check lint
      - name: Test with pytest
        run: |
          pip install -r tests/requirements.txt
          make
